# -*- coding: utf-8 -*-
"""Fin_Stock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OvekSC-exMUYj-8UXr1gnUg1XPLrucHz

## **0. Pre-Lims Code Test**

## **0.0 Install Project Deps**
"""

!pip install git+https://github.com/AI4Finance-Foundation/FinRL.git

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/MyDrive/Colab Notebooks/DRL/App/DRL/FinRL'
!ls

"""### **0.1 Surpress Datetime Errors**"""

import warnings
import datetime
from datetime import UTC

warnings.filterwarnings("ignore", category=DeprecationWarning)
# datetime.datetime.utcnow = lambda: datetime.datetime.now(UTC)
print("✅ Colab startup: datetime.utcnow patched.")

"""### **0.2 Test Colab Input Widgets**"""

from ipywidgets import IntText, FloatText, SelectMultiple, VBox
from IPython.display import display

# Widgets
decimal_input = FloatText(description="Decimal:")
integer_input = IntText(description="Integer:")
ticker_picker = SelectMultiple(
    options=['AAPL','AMZN','MSFT','GOOGL','TSLA','NVDA'],
    description="Tickers:"
)

# Display UI
display(VBox([decimal_input, integer_input, ticker_picker]))

# Access values
def get_inputs():
    dec = decimal_input.value
    integer = integer_input.value
    tickers = list(ticker_picker.value)
    return dec, integer, tickers

# Example usage:
dec, integer, tickers = get_inputs()
print(dec, integer, tickers)

"""## **1. Load Data**"""

import itertools
import pandas as pd

df = pd.read_csv('snp_500/all_stocks_5yr.csv')
df = df.rename(columns={'Name': 'tic'})
df.columns = df.columns.str.lower()
# Ensure date column is datetime
df['date'] = pd.to_datetime(df['date'], errors='coerce')

# tickers_input_string = "AAPL, MSFT, GOOGL" #@param {type:"string"}
# ✅ Define 15 prominent tickers
selected_tickers = [
    'AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META', 'TSLA', 'NVDA', 'BRK.B',
    'JPM', 'JNJ', 'V', 'PG', 'XOM', 'UNH', 'HD'
]

# Filter data for those tickers
subset_df = df[df['tic'].isin(selected_tickers)].copy()
offset = 15*100*10 +2
subset_df = subset_df.sort_values(["date", "tic"], ignore_index = True)
subset_df = subset_df.iloc[offset:]
print(len(subset_df))
print(subset_df.head())
print(subset_df.tail())
# Sort and reset
df = subset_df.sort_values(['tic', 'date']).reset_index(drop=True)
df

"""## **2. Set Split Train & Test Date Data**"""

from FinRl_Mods.feature_engineering import process_features

# --- Step 2: Feature Engineering ---
processed = process_features(df)

# --- Step 3: Environment Init ---
split_ratio = 0.8  #@param {type:"number"}
split_idx = int(len(df) * split_ratio)

TRAIN_START = df['date'].iloc[0]
TRAIN_END = df['date'].iloc[split_idx - 1]
TRADE_START = df['date'].iloc[split_idx]
TRADE_END = df['date'].iloc[-1]

"""## **3. Train**"""

from FinRl_Mods.env_initializer import init_stock_environment
from FinRl_Mods.agent_initializer import train_agent
# NB: 2-3 min
e_train_gym, e_trade_gym = init_stock_environment(processed, TRAIN_START, TRAIN_END, TRADE_START, TRADE_END)

# --- Step 4: Train Agent ---
trained_model = train_agent(e_train_gym, model_type="ppo", total_timesteps=50_000)

"""## **4. Backtest**"""

from finrl.plot import backtest_stats, get_baseline
from finrl.agents.stablebaselines3.models import DRLAgent
import matplotlib.pyplot as plt

# --- Step 5: Backtest ---
df_account_value_ppo, df_actions_ppo = DRLAgent.DRL_prediction(model=trained_model, environment=e_trade_gym)

perf_stats_all_ppo = backtest_stats(account_value=df_account_value_ppo)
perf_stats_all_ppo = pd.DataFrame(perf_stats_all_ppo)
# perf_stats_all_ppo.to_csv(
#     "./" + config.RESULTS_DIR + "/perf_stats_all_ppo_" + now + ".csv"
# )

def calc_cum_return(df):
    grouped = df.groupby('tic')
    selected_cum_ret = grouped.apply(lambda x: x['open']/x['open'].iloc[0])
    selected_cum_ret = selected_cum_ret.reset_index()
    selected_cum_ret = selected_cum_ret.set_index('level_1')
    selected_cum_ret = selected_cum_ret.join(df[['date']])

    return selected_cum_ret

import matplotlib.pyplot as plt

def plot_cum_return(selected_cum_ret):
    fig, ax = plt.subplots()

    # 个股
    for key, grp in selected_cum_ret.groupby(['tic']):
        ax = grp.plot(ax=ax, kind='line', x='date', y='open', label=key)

    plt.show()
# Plot state data Cummulative Returns
cum_ret = calc_cum_return(processed)
plot_cum_return(cum_ret)

# TODO: Get Data localy
# print("==============Get Baseline Stats===========")
# baseline_df = get_baseline(ticker="^DJI", start=TEST_START_DATE, end=TEST_END_DATE)
# stats = backtest_stats(baseline_df, value_col_name="close")
# print(f"✅ Backtest & baseline stats complete")

df_result_ppo = df_account_value_ppo.set_index(df_account_value_ppo.columns[0])
result = df_result_ppo
result.columns = ["ppo"]

print("result: ", result)
result.to_csv("result.csv")